/**
 * propDefs.js — Définitions par texture pour tous les objets du monde.
 *
 * Chaque texture a UNE définition partagée par toutes ses instances.
 * Plus de scale, blocksPlayer, collision, etc. par instance.
 * Tout est centralisé ici.
 *
 * AUTO-GENERATED by editor server — NE PAS MODIFIER MANUELLEMENT
 * (sauf pour le seed initial)
 */

export const PROP_DEFS = {
  'car': {
    scale: 2.236,
    isContainer: false,
    blocksPlayer: true,
    collision: { width: 276, height: 30, offsetX: 1, offsetY: -18 },
    specialType: null,
  },
  'hydrant': {
    scale: 2.42,
    isContainer: false,
    blocksPlayer: true,
    collision: { width: 33, height: 26, offsetX: 2, offsetY: -18 },
    specialType: null,
  },
  'banner-hor1': {
    scale: 1.78,
    isContainer: false,
    blocksPlayer: false,
    collision: null,
    specialType: null,
  },
  'banner-hor2': {
    scale: 0.6,
    isContainer: false,
    blocksPlayer: false,
    collision: null,
    specialType: null,
  },
  'fore': {
    scale: 0.99,
    isContainer: false,
    blocksPlayer: false,
    collision: null,
    specialType: null,
  },
  'barrel': {
    scale: 1.75,
    isContainer: true,
    blocksPlayer: true,
    collision: { width: 90, height: 22, offsetX: -1, offsetY: -3 },
    specialType: null,
  },
  'toolbox': {
    scale: 0.6094,
    isContainer: true,
    blocksPlayer: true,
    collision: { width: 40, height: 20, offsetX: 1, offsetY: -20 },
    specialType: null,
  },
  'coffrePlanque': {
    scale: 1,
    isContainer: true,
    blocksPlayer: true,
    collision: { width: 60, height: 18, offsetX: 0, offsetY: -31 },
    specialType: 'chest',
  },
  'workbench': {
    scale: 1,
    isContainer: true,
    blocksPlayer: true,
    collision: { width: 62, height: 15, offsetX: 0, offsetY: -33 },
    specialType: 'upgradeStation',
  },
};

/**
 * Retourne la définition d'un type de prop.
 * Fallback safe si le type n'existe pas.
 */
export function getPropDef(type) {
  return PROP_DEFS[type] ?? {
    scale: 1,
    isContainer: false,
    blocksPlayer: false,
    collision: null,
    specialType: null,
  };
}

